config:
  extensions:
    - '$spack/../tools/spack-scripting'
  build_stage: '$spack/../spack-stage'
  install_tree:
    projections:
      all: '{name}/{version}/{compiler.name}/{hash}'
  build_jobs: 12
  db_lock_timeout: 120
