config:
  extensions:
    - '$spack/../tools/spack-scripting'
  build_stage: '$spack/../spack-build_stage'
  test_stage: '$spack/../spack-test_stage'
  misc_cache: '$spack/../spack-misc_cache'
  build_jobs: 12
  db_lock_timeout: 120
