config:
  build_stage:
  - $SCRATCH/spack-stages/centos-8
  extensions:
  - /scratch-shared/meteoswiss/scratch/egermann/spack-mch/tools/spack-scripting
  install_path_scheme: '{name}/{version}/{compiler.name}/{hash}'
  install_tree: $SCRATCH/spack-install/centos-8
  module_roots:
    tcl: $SCRATCH/modules/centos-8
  source_cache: ~/.spack/source_cache
  template_dirs:
  - $spack/templates
