on:
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'On jenkins: https://jenkins-mch.cscs.ch/job/MeteoSwiss-APN/job/' + context.issue.repo +'/view/change-requests/job/PR-' + context.issue.number +'/'
            })
