name: Pull Request Docs Check

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: C2SM/sphinx-action@sphinx-latest
      with:
        pre-build-command: "pip install sphinx_rtd_theme && pip install sphinx-copybutton"
        build-command: "sphinx-build -b html . _build"
        docs-folder: "docs/"
    # Great extra actions to compose with:
    # Create an artifact of the html output.
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: docs/_build/
